# SERVICE IO SECTION
mongo_db: # MongoDB credentials
  mongo_connection_url: sample_text

feecc_io_gateway:
  gateway_address: http://127.0.0.1:8000
  autonomous_mode: true # disable io gateway interactions

# EXTERNAL IO SECTION
robonomics_network:
  enable_datalog: false # Whether to write certain data to Robonomics datalog or not
  account_address: "" # public address of the account in the Robonomics network
  account_seed: "" # seed of the account in the Robonomics network
  substrate_node_url: null # A url of the substrate node to be used

yourls: # Information about the yourls node used for short link creation
  server: ''
  username: ''
  password: ''


# PERIPHERALS SECTION
printer: # Info about the Brother Label printer used in your operation
  enable: true # if false - no printing tasks will work
  print_barcode: true
  print_qr: true # Whether to print QR code stickers pointing to a Passport in IPFS
  print_qr_only_for_composite: true
  qr_add_logos: false # Enables logo insertion into a qrcode
  print_security_tag: false # Whether to print seal tags with optional timestamp on them
  security_tag_add_timestamp: true


# WORKBENCH CONFIG SECTION
workbench_config:
  number: 1
  description: Монтажный стол 1 # optional description, leave blank if you don't need it

hardware: # list of attached devices to make use of
  camera_no: 1 # null or number

hid_devices_names: # known attached devices with their full names
  rfid_reader: "Sycreader RFID Technology Co., Ltd SYC ID&IC USB Reader"
  barcode_reader: "HENEX 2D Barcode Scanner"
