# SERVICE IO SECTION
api_server: # socket for the Api server to run on
  ip: "0.0.0.0"
  port: 5000

mongo_db: # MongoDB credentials
  mongo_connection_url: sample_text


# EXTERNAL IO SECTION
robonomics_network:
  enable_datalog: false # Whether to write certain data to Robonomics datalog or not
  account_address: "" # public address of the account in the Robonomics network
  account_seed: "" # seed of the account in the Robonomics network
  substrate_node_url: "" # A url of the substrate node to be used

pinata:
  enable: false # Enable pinning of files published to IPFS to Pinata

ipfs:
  enable: false

yourls: # Information about the yourls node used for short link creation
  server: ''
  username: ''
  password: ''


# PERIPHERALS SECTION
printer: # Info about the Brother Label printer used in your operation
  printer_model: "QL-800"
  paper_width: 62 # paper width in mm
  enable: false # if false - no printing tasks will work
  red: false # if black/red printing

print_barcode:
  enable: false

print_qr: # Whether to print QR code stickers pointing to a video in IPFS
  enable: false
  logos: false # Enables logo insertion into a qrcode

print_security_tag: # Whether to print seal tags with optional timestamp on them
  enable: false
  enable_timestamp: false


# WORKBENCH CONFIG SECTION
workbench_config:
  number: 1
  description: Монтажный стол 1 # optional description, leave blank if you don't need it
  api_socket: 192.168.66.19:5000  # a socket, at which the REST API of the device is listening on
  feecc_io_gateway_socket: ""
  hardware:  # list of attached devices to make use of
    camera: null # null or number

known_hid_devices: # known attached devices with their full names
  rfid_reader: "Sycreader RFID Technology Co., Ltd SYC ID&IC USB Reader"
  barcode_reader: "HENEX 2D Barcode Scanner"
