name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.5'
    - name: Install Poetry and Dev Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Codestyle check with Black
      run: |
        black -l 100 --exclude "test*" .
    - name: flake8 check
      run: |
        flake8 --count --max-line-length 100 .
